config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"
  get "/search" => "searchs#search"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get :followings, on: :member
    get :followers, on: :member
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence:true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy


  has_many :relationships, foreign_key: :following_id
  has_many :followings, through: :relationships, source: :follower

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :reverse_of_relationships, source: :following

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}


  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end

  def is_followed_by?(user)
    reverse_of_relationships.find_by(following_id: user.id).present?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except:[:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    comment.book_id = book.id
    comment.save
  end

  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to request.referer
  end


  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
    @q = Book.ransack(params[:q])
    @books = @q.result
  end

  def index
    @book_comment = BookComment.new
    @book = Book.new
    @q = Book.ransack(params[:q])
    @books = @q.result
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @q = Book.ransack(params[:q])
    @books = @q.result
    @book = Book.find(params[:id])
    if @book.user == current_user
      render :edit
    else
      redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :category, :rate)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def create
    following = current_user.relationships.build(follower_id: params[:user_id])
    following.save
    redirect_to request.referer
  end

  def destroy
    following = current_user.relationships.find_by(follower_id: params[:user_id])
    following.destroy
    redirect_to request.referer
  end
end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  def search
    @content = params["content"]
    @model = params["model"]
    @method = params["method"]
    @records = search_for(@content, @model, @method)
  end

  private
  def search_for(content, model, method)
    if model == "user"
      if method == "perfect"
        User.where(name: content)
      elsif method == "partial"
        User.where("name LIKE ?", "%"+content+"%")
      elsif method == "prefix"
        User.where("name LIKE ?", content+"%")
      elsif method == "backword"
        User.where("name LIKE ?", "%"+content)
      end
    elsif model == "book"
      if method == "perfect"
        Book.where(title: content)
      elsif method == "partial"
        Book.where("title LIKE ?", "%"+content+"%")
      elsif method == "prefix"
        Book.where("title LIKE ?", content+"%")
      elsif method == "backword"
        Book.where("title LIKE ?", "%"+content)
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @q = Book.ransack(params[:q])
  end

  def index
    @users = User.all
    @book = Book.new
    @q = Book.ransack(params[:q])
    @books = @q.result
  end

  def followings
    user = User.find(params[:id])
    @users = user.followings
    @q = Book.ransack(params[:q])
    @books = @q.result
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
    @q = Book.ransack(params[:q])
    @books = @q.result
  end

  def edit
    @user = User.find(params[:id])
    @q = Book.ransack(params[:q])
    @books = @q.result
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_book_comments.html.erb
<% book.book_comments.each do |book_comment|%>
  <div class = "d-flex flex-row">
    <div>
      <%= image_tag book_comment.user.get_profile_image, size:"40x40"%></br>
      <%= book_comment.user.name%>
    </div>
    <div style = "margin-left: 10px;"><%= book_comment.comment%></div>
    <div style = "margin-left: 10px;">
      <% if book_comment.user == current_user%>
        <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), class: "btn btn-danger btn-sm", method: :delete%>
      <%end%>
    </div>
  </div>
<%end%>

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class: 'form-control book_category' %>
  </div>
  <div class="form-group" id="rate">
    <%= f.label :rate%>
    <%= f.hidden_field :rate, id: :review_star %>
  </div>
  <script>
  $('#rate').raty({
    size     : 36,
    starOff:  '<%= asset_path('star-off.png') %>',
    starOn : '<%= asset_path('star-on.png') %>',

    scoreName: 'book[rate]',
    half: false,
  });
  </script>
  <div class="form-group">
    <%= f.submit "Create Book", class: "btn btn-success"%>
  </div>
<% end %>

app/views/books/_formedit.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="mb-3" id="star-rate<%= book.id%>"></div>
    <script>
      $('#star-rate<%= book.id%>').raty({
      size      : 36,
      starOff   : '<%= asset_path('star-off.png') %>',
      starOn    : '<%= asset_path('star-on.png') %>',
      half      : false,
      readOnly: true,
      score: <%= book.rate %>,
    });
     </script>
  <div class="form-group">
    <%= f.submit "Update Book", class: "btn btn-success"%>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>Img</th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th>Fav</th>
      <th>Comment</th>
      <th>Rate</th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to(book.user) do %>
          <%= image_tag book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= book.category%></td>
        <% if book.favorited_by?(current_user)%>
          <td>
            <%= link_to book_favorites_path(book), class: "text-danger", method: :delete do%>
               ♥<%= book.favorites.count%>
            <%end%>
          </td>
        <%else%>
          <td>
            <%= link_to book_favorites_path(book), class: "text-primary", method: :post do%>
               ♥<%= book.favorites.count%>
            <%end%>

          </td>
        <%end%>
        <td>コメント数:<%= book.book_comments.count%></td>
        <td>
          <div id="star-rate<%= book.id%>"></div>
          <script>
            $('#star-rate<%= book.id%>').raty({
              size      : 36,
              starOff   : '<%= asset_path('star-off.png') %>',
              starOn    : '<%= asset_path('star-on.png') %>',
              half      : false,
              readOnly: true,
              score: <%= book.rate %>,
            });
          </script>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/create.js.erb
$("#book_comment_comment").val("");

app/views/books/edit.html.erb
<div class='container'>
  <%= render 'layouts/errors', obj: @book%>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
  		<%= render 'formedit', book: @book %>
  		<%= link_to 'Show', @book, class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book%>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @book %>
      
      <div id="star-rate<%= @book.id%>"></div>
      <script>
        $('#star-rate<%= @book.id%>').raty({
          size      : 36,
          starOff   : '<%= asset_path('star-off.png') %>',
          starOn    : '<%= asset_path('star-on.png') %>',
          half      : false,
          readOnly: true,
          score: <%= @book.rate %>,
        });
      </script>
    </div>
      
    <div class='col-md-8 offset-md-1'>
       <h2>Books</h2>
        <%= sort_link(@q, :created_at, "新しい順") %> |
        <%= sort_link(@q, :rate, "評価の高い順") %>
       <%= render 'index', books: @books%>
    </div>
    
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: @newbook %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
          <td><%= link_to(@book.user) do %>
            <%= image_tag @book.user.get_profile_image, size:"50x50" %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, @book %></td>
          <td><%= @book.body %></td>
          <td><%= @book.category%></td>
          <% if @book.favorited_by?(current_user)%>
            <td>
              <div>
                <%= link_to book_favorites_path(@book), class: "text-danger", method: :delete do%>
                  ♥<%= @book.favorites.count%>
                <%end%>
              </div>
            </td>
          <%else%>
            <td>
              <div>
                <%= link_to book_favorites_path(@book), class: "text-primary", method: :post do%>
                  ♥<%= @book.favorites.count%>
                <%end%>
              </div>
            </td>
          <%end%>
            <td>コメント数:<%= @book.book_comments.count %></td>
            <td>
              <div id="star-rate<%= @book.id%>"></div>
              <script>
                $('#star-rate<%= @book.id%>').raty({
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  half      : false,
                  readOnly: true,
                  score: <%= @book.rate %>,
                });
              </script>
            </td>
            <%if @book.user == current_user%>
              <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
              <td><%= link_to 'Destroy', @book, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
            <%end%>
        </tr>
      </table>

      <div class = "comments">
        <%= render 'books/book_comments', book: @book%>
      </div>

      <div>
          <%= form_with model: [@book, @book_comment], local: false do |f|%>
           <%= f.text_area :comment,rows:"5", class: "w-100"%>
           <%= f.submit "送信"%>
          <%end%>
      </div>

    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to 'Log in',new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3 sign_in" %>
        </div>
        <div class="row">
          <%= link_to 'Sign Up',new_user_registration_path, class: "btn btn-success btn-sm btn-block sign_up" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/searchs/_index_books.html.erb
<div class = "container">
  <div class = "row">
    <table class = "table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% books.each do |book|%>
        <tr>
          <td><%= image_tag book.user.get_profile_image, size: '50x50' %></td>
          <td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
          <td><%= book.body %></td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/searchs/_index_users.html.erb
<div class = "container">
  <div class = "row">
    <table class = "table">
      <thead>
        <tr>
          <th>Image</th>
          <th>Name</th>
          <th>Introduction</th>
        </tr>
      </thead>
      <tbody>
        <% users.each do |user|%>
        <tr>
          <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
          <td><%= user.name%></td>
          <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

app/views/searchs/_search.html.erb
<% if user_signed_in?%>
  <%= form_tag(search_path, method: :get) do%>
  <div class = "text-center">
    <div>
      <%= text_field_tag "content"%>
      <%= select_tag "model", options_for_select({"User" => "user", "Book" => "book"})%>
      <%= select_tag "method", options_for_select({"完全一致" => "perfect", "部分一致" => "partial", "前方一致" => "prefix", "後方一致" => "backword"})%>
      <%= submit_tag "検索"%>
    </div>
  </div>
  <%end%>
<%end%>

app/views/searchs/search.html.erb
<% if @model == "user"%>
  <h3>Users search for "<%= @content%>"</h3>
  <%= render "searchs/index_users", users: @records%>
<%elsif @model == "book"%>
  <h3>Books search for "<%= @content%>"</h3>
  <%= render "searchs/index_books", books: @records%>
<%end%>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>
          <% if user != current_user%>
            <% if user.is_followed_by?(current_user)%>
              <%= link_to "フォロー外す", user_relationships_path(user), method: :delete%>
            <%else%>
              <%= link_to "フォローする", user_relationships_path(user), method: :post%>
            <%end%>
          <%end%>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count, followings_user_path(user.id)%></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count, followers_user_path(user.id)%></th>
  </tr>
</table>

<div class='row'>
  <% if user == current_user%>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
      <i class="fas fa-user-cog"></i>
    <%end%>
  <%elsif user.is_followed_by?(current_user)%>
      <%=link_to user_relationships_path(user), method: :delete do%>
        <bottun class = "btn btn-info">フォロー外す</bottun>
      <%end%>
  <%else%>
      <%=link_to user_relationships_path(user), method: :post do%>
        <bottun class = "btn btn-success">フォローする</bottun>
      <%end%>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class = "container">
  <h1>Follower Users</h1>
  <% if @users.any?%>
    <div class = "row">
      <table class = "table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user|%>
          <tr>
            <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
            <td><%= user.name %></td>
            <td>フォロー数:<%= user.followings.count%></td>
            <td>フォロワー数:<%= user.followers.count%></td>
            <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  <%else%>
  <p>ユーザーはいません</p>
  <%end%>
</div>

app/views/users/followings.html.erb
<div class = "container">
  <h1>Follow Users</h1>
  <% if @users.any?%>
    <div class = "row">
      <table class = "table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user|%>
          <tr>
          <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
          <td><%= user.name %></td>
          <td>フォロー数:<%= user.followings.count%></td>
          <td>フォロワー数:<%= user.followers.count%></td>
          <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
          </tr>
          <%end%>
        </tbody>
      </table>
    </div>
  <%else%>
  <p>ユーザーはいません</p>
  <%end%>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
    </div>
  </div>
</div>